<?php

/* SERACH */
acf_add_local_field_group(array(
    'key' => 'group_612ceeef98ddd',
    'title' => 'Rek.ai',
    'fields' => array(
        array(
            'key' => 'field_618a936a55576',
            'label' => 'Enable',
            'name' => 'rekai_enable',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
                'width' => '15%',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
        array(
            'key' => 'field_61288d47b2222',
            'label' => 'ID',
            'name' => 'rekai_id',
            'type' => 'text',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_618a936a55576',
                        'operator' => '==',
                        'value' => 1,
                    ),
                ),
            )
,            'wrapper' => array(
                'width' => '30%',
                'class' => '',
                'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'prepend' => '',
            'append' => '',
            'maxlength' => '',
        ),
        array(
            'key' => 'field_618a936a55577',
            'label' => 'Autocomplete search',
            'name' => 'rekai_autocomplete',
            'type' => 'true_false',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
                array(
                    array(
                        'field' => 'field_61288d47b2222',
                        'operator' => '!=',
                        'value' => '',
                    ),
                ),
            ),
            'wrapper' => array(
                'width' => '15%',
                'class' => '',
                'id' => '',
            ),
            'show_in_rest' => 0,
            'message' => '',
            'default_value' => 0,
            'ui' => 0,
            'ui_on_text' => '',
            'ui_off_text' => '',
        ),
    ),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-admin',
            ),
        ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => true,
    'description' => '',
));
acf_add_local_field_group(array(
	'key' => 'group_63d308a9e2073',
	'title' => 'Aktivera behörighetsstyrning per användare',
	'fields' => array(
		array(
			'key' => 'field_63d308aacd562',
			'label' => 'Mellanstartsida',
			'name' => 'user_permissions_hk_quick',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20%',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_63d30a55ce3a2',
			'label' => 'Bubblare',
			'name' => 'user_permissions_hk_bubble',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20%',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_63d30a66b5672',
			'label' => 'Debattforum',
			'name' => 'user_permissions_hk_forum',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20%',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_63d30ae7fc6a2',
			'label' => 'Kontakter',
			'name' => 'user_permissions_hk_kontakter',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20%',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_63d30c2b4b7d2',
			'label' => 'Driftstörningar',
			'name' => 'user_permissions_driftstorningar',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20%',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),

	),
    'location' => array(
        array(
            array(
                'param' => 'options_page',
                'operator' => '==',
                'value' => 'acf-options-admin',
            ),
        ),
    ),
	'menu_order' => 10,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );


