<?php

$hk_quick = get_field('user_permissions_hk_quick', 'options') ? array(
    'key' => 'field_63d308aacd56e',
    'label' => 'Mellanstartsida',
    'name' => 'user_can_edit_hk_quick',
    'aria-label' => '',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'message' => '',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
) : array();
$hk_bubble = get_field('user_permissions_hk_bubble', 'options') ? array(
    'key' => 'field_63d30a55ce3ad',
    'label' => 'Bubblare',
    'name' => 'user_can_edit_hk_bubble',
    'aria-label' => '',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'message' => '',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
) : array();
$hk_forum = get_field('user_permissions_hk_forum', 'options') ? array(
    'key' => 'field_63d30a66b5671',
    'label' => 'Debattforum',
    'name' => 'user_can_edit_hk_forum',
    'aria-label' => '',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'message' => '',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
) : array();
$hk_kontakter = get_field('user_permissions_hk_kontakter', 'options') ? array(
    'key' => 'field_63d30ae7fc6a1',
    'label' => 'Kontakter',
    'name' => 'user_can_edit_hk_kontakter',
    'aria-label' => '',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'message' => '',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
) : array();
$driftstorningar = get_field('user_permissions_driftstorningar', 'options') ? array(
    'key' => 'field_63d30c2b4b7d6',
    'label' => 'Driftstörningar',
    'name' => 'user_can_edit_driftstorningar',
    'aria-label' => '',
    'type' => 'true_false',
    'instructions' => '',
    'required' => 0,
    'conditional_logic' => 0,
    'wrapper' => array(
        'width' => '',
        'class' => '',
        'id' => '',
    ),
    'message' => '',
    'default_value' => 0,
    'ui' => 0,
    'ui_on_text' => '',
    'ui_off_text' => '',
) : array();

acf_add_local_field_group(array(
	'key' => 'group_63d308a9e2071',
	'title' => 'Behörigheter',
	'fields' => array(
		$hk_quick,
        $hk_bubble,
        $hk_forum,
		$hk_kontakter,
		$driftstorningar,
		array(
			'key' => 'field_63d30cec7860a',
			'label' => 'Hultsfred admin',
			'name' => 'user_can_edit_hultsfred_admin',
			'aria-label' => '',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 0,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'user_form',
				'operator' => '==',
				'value' => 'edit',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));
